### ISSUE TITLE
Non responsive extension

### ISSUE THREAD

**Issue by isdj** [AviH0/DigmiXport#1]
Hi, the extension is non-responsive.
Tried downgrading firefox to older version, no success.

**Comment by AviH0** [comment]
hey,
could you post the details of the exception and the stack trace?
Also, are you using the latest version of firefox?
Thanks for the feedback!

**Comment by isdj** [comment]
Solved the original error, was user specific.
I still have the following problem:
TypeError: courseData.lessons[courseLect] is undefined xport.js:40:18
Will help with the debug over the weekend if not solved. Sorry for being unhelpful

**Comment by AviH0** [comment]
Ok cool.
don't worry about debugging, the code is currently a mess...
could you try clearing site cookies and trying again?
If the problem persists, could you post a dump of the website cookies?

**Comment by isdj** [comment]
Cleared cookies without success.

created random schedule – cookies:



[{

              "Host raw": "http://www.digmi.org/huji",

              "Name raw": "0_courses",

              "Path raw": "/huji",

              "Content raw": "%7B%2267101%22%3A%7B%22%D7%A9%D7%A2%D7%95%D7%A8%22%3A0%2C%22%D7%AA%D7%A8%D7%92%22%3A6%2C%22%D7%9E%D7%A2%D7%91%22%3A34%7D%2C%2267109%22%3A%7B%22%D7%A9%D7%A2%D7%95%D7%A8%22%3A0%2C%22%D7%AA%D7%A8%D7%92%22%3A4%7D%2C%2267315%22%3A%7B%22%D7%A9%D7%A2%D7%95%D7%A8%22%3A0%2C%22%D7%AA%D7%A8%D7%92%22%3A20%7D%2C%2268100%22%3A%7B%22%D7%A1%D7%93%D7%A0%D7%94%22%3A0%7D%2C%2280131%22%3A%7B%22%D7%A9%D7%A2%D7%95%D7%A8%22%3A1%2C%22%D7%AA%D7%A8%D7%92%22%3A14%7D%2C%2280132%22%3A%7B%22%D7%A9%D7%A2%D7%95%D7%A8%22%3A0%2C%22%D7%AA%D7%A8%D7%92%22%3A2%7D%2C%2280134%22%3A%7B%22%D7%A9%D7%A2%D7%95%D7%A8%22%3A2%2C%22%D7%AA%D7%A8%D7%92%22%3A11%7D%2C%2280135%22%3A%7B%22%D7%A9%D7%A2%D7%95%D7%A8%22%3A0%2C%22%D7%AA%D7%A8%D7%92%22%3A4%7D%2C%2280181%22%3A%7B%22%D7%A9%D7%A2%D7%95%D7%A8%22%3A1%2C%22%D7%AA%D7%A8%D7%92%22%3A7%7D%2C%2280200%22%3A%7B%22%D7%A9%D7%A2%D7%95%D7%A8%22%3A0%2C%22%D7%AA%D7%A8%D7%92%22%3A1%7D%7D",

              "Expires": "At the end of the session",

              "Expires raw": "0",

              "Send for": "Any type of connection",

              "Send for raw": "false",

              "HTTP only raw": "false",

              "SameSite raw": "no_restriction",

              "This domain only": "Valid for host only",

              "This domain only raw": "true",

              "Store raw": "firefox-default",

              "First Party Domain": ""

},

{

              "Host raw": "http://www.digmi.org/huji",

              "Name raw": "%D7%90%D7%99%D7%99%D7%96%D7%99%D7%A7_courses",

              "Path raw": "/huji",

              "Content raw": "%7B%2267101%22%3A%7B%22%D7%A9%D7%A2%D7%95%D7%A8%22%3A0%2C%22%D7%AA%D7%A8%D7%92%22%3A6%2C%22%D7%9E%D7%A2%D7%91%22%3A34%7D%2C%2267109%22%3A%7B%22%D7%A9%D7%A2%D7%95%D7%A8%22%3A0%2C%22%D7%AA%D7%A8%D7%92%22%3A4%7D%2C%2267315%22%3A%7B%22%D7%A9%D7%A2%D7%95%D7%A8%22%3A0%2C%22%D7%AA%D7%A8%D7%92%22%3A20%7D%2C%2268100%22%3A%7B%22%D7%A1%D7%93%D7%A0%D7%94%22%3A0%7D%2C%2280131%22%3A%7B%22%D7%A9%D7%A2%D7%95%D7%A8%22%3A1%2C%22%D7%AA%D7%A8%D7%92%22%3A14%7D%2C%2280132%22%3A%7B%22%D7%A9%D7%A2%D7%95%D7%A8%22%3A0%2C%22%D7%AA%D7%A8%D7%92%22%3A2%7D%2C%2280134%22%3A%7B%22%D7%A9%D7%A2%D7%95%D7%A8%22%3A2%2C%22%D7%AA%D7%A8%D7%92%22%3A11%7D%2C%2280135%22%3A%7B%22%D7%A9%D7%A2%D7%95%D7%A8%22%3A0%2C%22%D7%AA%D7%A8%D7%92%22%3A4%7D%2C%2280181%22%3A%7B%22%D7%A9%D7%A2%D7%95%D7%A8%22%3A1%2C%22%D7%AA%D7%A8%D7%92%22%3A7%7D%2C%2280200%22%3A%7B%22%D7%A9%D7%A2%D7%95%D7%A8%22%3A0%2C%22%D7%AA%D7%A8%D7%92%22%3A1%7D%7D",

              "Expires": "At the end of the session",

              "Expires raw": "0",

              "Send for": "Any type of connection",

              "Send for raw": "false",

              "HTTP only raw": "false",

              "SameSite raw": "no_restriction",

              "This domain only": "Valid for host only",

              "This domain only raw": "true",

              "Store raw": "firefox-default",

              "First Party Domain": ""

},

{

              "Host raw": "http://www.digmi.org/huji",

              "Name raw": "saves",

              "Path raw": "/huji",

              "Content raw": "%5B0%2C%22%D7%90%D7%99%D7%99%D7%96%D7%99%D7%A7%22%5D",

              "Expires": "At the end of the session",

              "Expires raw": "0",

              "Send for": "Any type of connection",

              "Send for raw": "false",

              "HTTP only raw": "false",

              "SameSite raw": "no_restriction",

              "This domain only": "Valid for host only",

              "This domain only raw": "true",

              "Store raw": "firefox-default",

              "First Party Domain": ""

},

{

              "Host raw": "http://www.digmi.org/huji",

              "Name raw": "0_courses",

              "Path raw": "/huji",

              "Content raw": "%7B%221480%22%3A%7B%22%D7%A9%D7%95%D7%AA%22%3A0%7D%7D",

              "Expires": "At the end of the session",

              "Expires raw": "0",

              "Send for": "Any type of connection",

              "Send for raw": "false",

              "HTTP only raw": "false",

              "SameSite raw": "no_restriction",

              "This domain only": "Valid for host only",

              "This domain only raw": "true",

              "Store raw": "firefox-private",

              "First Party Domain": ""

}]

**Comment by AviH0** [comment]
I'm not sure I managed to completely recreate your issue, but I have attempted to fix it. Your add-on should auto-update in a few minutes, please let me know if the issue persists.

**Comment by AviH0** [comment]
Thanks, that was really helpful 👍

**Comment by isdj** [comment]
Thank you for the extension, it's great!
