### ISSUE TITLE
Buttons not responding

### ISSUE THREAD

**Issue by aviramyi** [AviH0/DigmiXport#7]
Hi there! thank you for this great addon. 
I am using Chrome, and when I try to export my digmi table to my Google calendar there's seems to be no response from the addon. 
After it finished phrasing the data, both the ics file button and the "Export to Google Calendar" buttons are unresponsive.
I have tried any combination of checking and unchecking the "Lesson events" and "Exam events" checkboxes, and even downloaded Firefox and installed the addon there and I can't get it to work.
Thank you in advance!

**Comment by AviH0** [comment]
Hi,
you're welcome, I hope we can get it to work for you. 
If you save the schedule you created in Digmi and then load it, you will see a long url in your address bar. Could you copy that url and paste it here?

**Comment by aviramyi** [comment]
Sure:
https://www.digmi.org/huji/?%7B%2267109%22%3A%7B%22%u05E9%u05E2%u05D5%u05E8%22%3A0%2C%22%u05EA%u05E8%u05D2%22%3A5%7D%2C%2267315%22%3A%7B%22%u05E9%u05E2%u05D5%u05E8%22%3A0%2C%22%u05EA%u05E8%u05D2%22%3A9%7D%2C%2280133%22%3A%7B%22%u05E9%u05E2%u05D5%u05E8%22%3A0%2C%22%u05EA%u05E8%u05D2%22%3A5%7D%2C%2280135%22%3A%7B%22%u05E9%u05E2%u05D5%u05E8%22%3A1%2C%22%u05EA%u05E8%u05D2%22%3A4%7D%7D

**Comment by AviH0** [comment]
Could you please try clearing your cookies? if you saved any schedules on Digmi, this will delete them. You can save them by copying the url like you did with this schedule and later restore them.
After clearing the cookies, try following the url you pasted above. You must then make a change to the schedule (you can change some course's details and then change them back). Then try exporting again and let me know if there is a change.

**Comment by aviramyi** [comment]
It helped, now I can download the ics file and add it directly to the google calendar, but only if I uncheck the Exam checkbox. I can add the exams manually if it's a problem on my end. Thank you!

**Comment by AviH0** [comment]
Ok. I have identified a bug with exam parsing resulting from a change in configurations in Shanton. I will update the add-on soon and then exams can be exported as well (although the information will be coming from Shanton and may not be fully updated yet).
