### ISSUE TITLE
all events are one year early

### ISSUE THREAD

**Issue by aviramyi** [AviH0/DigmiXport#8]
Hi, thanks again for the extension.
While exporting to google calendar on chrome, everything works well except for the fact that all the events are created in 2019-2020 instead of 2020-2021.

Thanks!

**Comment by AviH0** [comment]
Hi,
This is due to the yearly schedule not having been updated on the university website.
I might implement some kind of workaround, but at the moment I suggest waiting a little longer, as shnaton info is also still likely to change somewhat.

**Comment by AviH0** [comment]
I have fixed the issue for now, and the fix will be up as soon as it passes review. Watch for version 1.15.12 on the google store.
