### ISSUE TITLE
don't sucsess

### ISSUE THREAD

**Issue by Kfirm1995** [AviH0/DigmiXport#9]
it's stuck on this 
![2020-09-10](https://user-images.githubusercontent.com/71077435/92763366-1fab7700-f39c-11ea-9480-8ce903cc6327.png)

**Comment by AviH0** [comment]
Hi, I've identified the issue and uploaded a fix, which you can use as soon as it passes review (you will see the version number in the google store will be 1.5.13).
Thanks for catching this bug!

**Comment by Kfirm1995** [comment]
בכיף

בתאריך יום ה׳, 10 בספט׳ 2020, 20:43, מאת AviH0 ‏<notifications@github.com>:
